//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugHunter.CsRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugHunter.CsRules.CsResources", typeof(CsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEvent called with event type &apos;{0}&apos;, use &apos;EventType.{1}&apos; instead..
        /// </summary>
        internal static string EventLogArguments_Description {
            get {
                return ResourceManager.GetString("EventLogArguments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEvent called with event type &apos;{0}&apos;..
        /// </summary>
        internal static string EventLogArguments_MessageFormat {
            get {
                return ResourceManager.GetString("EventLogArguments_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEvent should not be called with hardcoded event type..
        /// </summary>
        internal static string EventLogArguments_Title {
            get {
                return ResourceManager.GetString("EventLogArguments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Session[]&apos; should not be used. Use &apos;SessionHelper.GetValue()&apos; instead..
        /// </summary>
        internal static string HttpSessionElementAccessGet_Description {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessGet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be used. Use &apos;SessionHelper.GetValue()&apos; instead..
        /// </summary>
        internal static string HttpSessionElementAccessGet_MessageFormat {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessGet_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Session[]&apos; should not be used. Use &apos;SessionHelper.GetValue()&apos; instead..
        /// </summary>
        internal static string HttpSessionElementAccessGet_Title {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessGet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Session[]&apos; should not be used. Use &apos;SessionHelper.SetValue()&apos;  instead..
        /// </summary>
        internal static string HttpSessionElementAccessSet_Description {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessSet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be used. Use &apos;SessionHelper.SetValue()&apos; instead..
        /// </summary>
        internal static string HttpSessionElementAccessSet_MessageFormat {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessSet_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Session[]&apos; should not be used. Use &apos;SessionHelper.SetValue()&apos;  instead..
        /// </summary>
        internal static string HttpSessionElementAccessSet_Title {
            get {
                return ResourceManager.GetString("HttpSessionElementAccessSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when redirecting to external URL..
        /// </summary>
        internal static string RedirectCodeFixExternal {
            get {
                return ResourceManager.GetString("RedirectCodeFixExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when redirecting to local URL..
        /// </summary>
        internal static string RedirectCodeFixLocal {
            get {
                return ResourceManager.GetString("RedirectCodeFixLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using one of &apos;WhereStartsWith()&apos;, &apos;WhereEndsWith()&apos; or &apos;WhereContains()&apos; methods instead..
        /// </summary>
        internal static string WhereLikeMethod_Description {
            get {
                return ResourceManager.GetString("WhereLikeMethod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{1}&apos; should not be used..
        /// </summary>
        internal static string WhereLikeMethod_MessageFormat {
            get {
                return ResourceManager.GetString("WhereLikeMethod_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;WhereLike()&apos; or &apos;WhereNotLike()&apos; should not be used used..
        /// </summary>
        internal static string WhereLikeMethod_Title {
            get {
                return ResourceManager.GetString("WhereLikeMethod_Title", resourceCulture);
            }
        }
    }
}
